service: number-facts-register

provider:
  name: aws
  runtime: nodejs6.10
  environment:
    DYNAMODB_TABLE: number-facts-${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

functions:
  register:
    handler: handler.register
    events:
      - http:
          path: register
          method: post
          cors: true
